"""
Pencil calculus (paper §8, "Pencils and their constraints"):

Builds the paper's "example of a pencil of three conics": a 3-pencil
  P = p1 ^ p2 ^ p3 ^ Iod
through three points, an orthogonal basis Cr, Cg, Cb of conics extracted from
P via the right complement, and verifies:

  Def 12 (orthogonality):        A perp B  <=>  A ^ B^c == 0
  Th 10  (wedging-rc-general):   (A v B) ^ B^c == A           for orthogonal blades A, B
  Th 11  (constraint-remove-conic): P ^ C^c == the conics of P orthogonal to C
  Th 9   (constraint-add-point):    P ^ p  == the conics of P through p
  Th 8   (constraint-add-conic):    P v C  == pencil generated by P and C (order + 1)
  P == Cr v Cg v Cb   (the orthogonal basis spans P)

Theorem 12 (constraint-remove-point: P v p^c == P' where P = P' ^ p) is NOT
verified here.  A grade-counting argument shows it can never be reached
non-vacuously: for p a 1-PSE and P = P' ^ p a pencil, p in NO(P) forces
gr(P') >= 2, so gr(P' ^ p^c) = gr(P') + 7 > 8 is *always* zero for trivial
(dimension) reasons, never because P' and p have disjoint null-basis support
(the genuine Def.12 orthogonality that makes Th 10's proof go through, cf.
the toy cases in this file's history). Concrete instantiations of
(A ^ B) v B^c with A = P' = p1^p2^p3^Iod^p4 (grade 6), B = p5 (the structure
required by Th 12) do not reproduce A. See CCGA_cheat_sheet.md §8a.
"""
import pytest

from ccga.point import point
from ccga.algebra import Iod
from ccga.operations import (
    right_complement, meet, grades, is_zero, norm, orthogonal, proportional,
)

TOL = 1e-6


def _normalize(mv):
    return mv / norm(mv)


@pytest.fixture(scope="module")
def pencil_basis():
    pts = [point(x, y) for x, y in
           [(0.3, 1.7), (2.1, -0.4), (-1.2, 0.8), (1.5, 2.3), (-0.7, -1.1), (2.8, 0.6)]]
    p1, p2, p3, p4, p5, p6 = pts

    P = _normalize(p1 ^ p2 ^ p3 ^ Iod)              # 3-pencil through p1,p2,p3
    Cr = _normalize(P ^ p4 ^ p5)                     # conic through p1..p5
    Cg = _normalize(P ^ right_complement(Cr) ^ p6)   # orthogonal to Cr, through p6
    Cb = _normalize(P ^ right_complement(Cr) ^ right_complement(Cg))
    return dict(pts=pts, P=P, Cr=Cr, Cg=Cg, Cb=Cb)


def test_grades(pencil_basis):
    assert grades(pencil_basis["P"]) == [5]
    for name in ("Cr", "Cg", "Cb"):
        assert grades(pencil_basis[name]) == [7]


def test_def12_orthogonal_basis(pencil_basis):
    Cr, Cg, Cb = (pencil_basis[k] for k in ("Cr", "Cg", "Cb"))
    assert orthogonal(Cg, Cr)
    assert orthogonal(Cb, Cr)
    assert orthogonal(Cb, Cg)
    assert not orthogonal(Cr, Cr)


def test_P_equals_Cr_vee_Cg_vee_Cb(pencil_basis):
    P, Cr, Cg, Cb = (pencil_basis[k] for k in ("P", "Cr", "Cg", "Cb"))
    ok, ratio = proportional(P, meet(meet(Cr, Cg), Cb))
    assert ok
    assert abs(ratio) > TOL


def test_theorem10_wedging_rc_general(pencil_basis):
    """(A v B) ^ B^c == A  for orthogonal blades A, B."""
    Cr, Cg, Cb = (pencil_basis[k] for k in ("Cr", "Cg", "Cb"))
    ok, _ = proportional(meet(Cr, Cg) ^ right_complement(Cg), Cr)
    assert ok
    ok, _ = proportional(meet(Cg, Cb) ^ right_complement(Cb), Cg)
    assert ok


def test_theorem11_constraint_remove_conic(pencil_basis):
    """P ^ C^c is the pencil of conics of P orthogonal to C."""
    P, Cr, Cg, Cb = (pencil_basis[k] for k in ("P", "Cr", "Cg", "Cb"))
    ok, _ = proportional(P ^ right_complement(Cb), meet(Cr, Cg))
    assert ok
    ok, _ = proportional(P ^ right_complement(Cg), meet(Cr, Cb))
    assert ok


def test_theorem9_constraint_add_point(pencil_basis):
    """P ^ p is the pencil of conics of P passing through p."""
    pts, P = pencil_basis["pts"], pencil_basis["P"]
    p1, p2, p3, p4, p5, p6 = pts

    Q = _normalize(P ^ p4)              # 2-pencil through p1,p2,p3,p4
    assert grades(Q) == [6]

    Cr_in_Q = _normalize(Q ^ p5)        # conic through p1..p5 -- "in" Q
    assert is_zero(meet(Q, Cr_in_Q), TOL)

    # conic through p1, p2 and 3 fresh points: not in P, hence not in Q either
    q1, q2, q3 = point(5.0, 1.0), point(-3.0, 4.0), point(0.5, -2.5)
    C_other = _normalize(p1 ^ p2 ^ q1 ^ q2 ^ q3 ^ Iod)
    assert not is_zero(meet(P, C_other), TOL)
    assert not is_zero(meet(Q, C_other), TOL)


def test_theorem8_constraint_add_conic(pencil_basis):
    """P v C is the pencil of order k+1 generated by all conics of P and C."""
    pts = pencil_basis["pts"]
    p1, p2 = pts[0], pts[1]
    P, Cr, Cg, Cb = (pencil_basis[k] for k in ("P", "Cr", "Cg", "Cb"))

    q1, q2, q3 = point(5.0, 1.0), point(-3.0, 4.0), point(0.5, -2.5)
    C = _normalize(p1 ^ p2 ^ q1 ^ q2 ^ q3 ^ Iod)
    assert not is_zero(meet(P, C), TOL)     # C not in P (order-3 pencil)

    Q = meet(P, C)
    assert grades(Q) == [4]                 # order 3 -> order 4

    for conic in (Cr, Cg, Cb, C):
        assert is_zero(meet(Q, conic), TOL)
